<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="recipeManger" nsURI="platform:/resource/recipeManger/model/RecipeManger.ecore"
    nsPrefix="recipeManger">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="TODO: Add documentation for recipeManger. Hint: You may copy this element in the Ecore editor to add documentation to EClasses, EOperations, ..."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Recipe">
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" upperBound="-1" eType="#//Rating"
        containment="true" eOpposite="#//Rating/Bewertet"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Duration" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Difficulty" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredUtilities" upperBound="-1"
        eType="#//KitchenUtensil"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foodCategory" upperBound="-1"
        eType="#//FoodCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasIngredients" upperBound="-1"
        eType="#//Ingredient" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasRecipes" upperBound="-1"
        eType="#//Recipe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasVeganismLevel" lowerBound="1"
        eType="#//VeganismLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ingredient">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Amount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Unit" lowerBound="1" eType="#//Unit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasVeganismLevel" lowerBound="1"
        eType="#//VeganismLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FoodCategory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Author">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isOwner" upperBound="-1"
        eType="#//Recipe" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Email" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writes" upperBound="-1"
        eType="#//Rating" eOpposite="#//Rating/geschriebenVon"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calls" eType="#//Recipe"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rating">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Stars" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Bewertet" lowerBound="1"
        eType="#//Recipe" eOpposite="#//Recipe/has"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geschriebenVon" lowerBound="1"
        eType="#//Author" eOpposite="#//Author/writes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Unit">
    <eLiterals name="ml"/>
    <eLiterals name="l" value="1"/>
    <eLiterals name="g" value="2"/>
    <eLiterals name="kg" value="3"/>
    <eLiterals name="tsp" value="4"/>
    <eLiterals name="mg" value="5"/>
    <eLiterals name="tbsp" value="6"/>
    <eLiterals name="pcs" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KitchenUtensil">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecipeManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kitchenUtensil" upperBound="-1"
        eType="#//KitchenUtensil" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foodCategory" upperBound="-1"
        eType="#//FoodCategory" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" upperBound="-1"
        eType="#//Author" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="veganismLevel" lowerBound="3"
        upperBound="3" eType="#//VeganismLevel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VeganismLevel" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Vegan" eSuperTypes="#//VeganismLevel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Carnivorous" eSuperTypes="#//VeganismLevel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Vegetaric" eSuperTypes="#//VeganismLevel"/>
</ecore:EPackage>
