/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.Author;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Rating;
import org.xtext.example.mydsl.myDsl.Recipe;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rating</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.RatingImpl#getStars <em>Stars</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.RatingImpl#getComment <em>Comment</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.RatingImpl#getBewertet <em>Bewertet</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.RatingImpl#getWrittenBy <em>Written By</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RatingImpl extends MinimalEObjectImpl.Container implements Rating
{
  /**
   * The default value of the '{@link #getStars() <em>Stars</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStars()
   * @generated
   * @ordered
   */
  protected static final int STARS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getStars() <em>Stars</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStars()
   * @generated
   * @ordered
   */
  protected int stars = STARS_EDEFAULT;

  /**
   * The default value of the '{@link #getComment() <em>Comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComment()
   * @generated
   * @ordered
   */
  protected static final String COMMENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getComment() <em>Comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComment()
   * @generated
   * @ordered
   */
  protected String comment = COMMENT_EDEFAULT;

  /**
   * The cached value of the '{@link #getBewertet() <em>Bewertet</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBewertet()
   * @generated
   * @ordered
   */
  protected Recipe bewertet;

  /**
   * The cached value of the '{@link #getWrittenBy() <em>Written By</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWrittenBy()
   * @generated
   * @ordered
   */
  protected Author writtenBy;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RatingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.RATING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getStars()
  {
    return stars;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStars(int newStars)
  {
    int oldStars = stars;
    stars = newStars;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.RATING__STARS, oldStars, stars));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getComment()
  {
    return comment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setComment(String newComment)
  {
    String oldComment = comment;
    comment = newComment;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.RATING__COMMENT, oldComment, comment));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Recipe getBewertet()
  {
    if (bewertet != null && bewertet.eIsProxy())
    {
      InternalEObject oldBewertet = (InternalEObject)bewertet;
      bewertet = (Recipe)eResolveProxy(oldBewertet);
      if (bewertet != oldBewertet)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.RATING__BEWERTET, oldBewertet, bewertet));
      }
    }
    return bewertet;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Recipe basicGetBewertet()
  {
    return bewertet;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBewertet(Recipe newBewertet)
  {
    Recipe oldBewertet = bewertet;
    bewertet = newBewertet;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.RATING__BEWERTET, oldBewertet, bewertet));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Author getWrittenBy()
  {
    if (writtenBy != null && writtenBy.eIsProxy())
    {
      InternalEObject oldWrittenBy = (InternalEObject)writtenBy;
      writtenBy = (Author)eResolveProxy(oldWrittenBy);
      if (writtenBy != oldWrittenBy)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.RATING__WRITTEN_BY, oldWrittenBy, writtenBy));
      }
    }
    return writtenBy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Author basicGetWrittenBy()
  {
    return writtenBy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setWrittenBy(Author newWrittenBy)
  {
    Author oldWrittenBy = writtenBy;
    writtenBy = newWrittenBy;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.RATING__WRITTEN_BY, oldWrittenBy, writtenBy));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.RATING__STARS:
        return getStars();
      case MyDslPackage.RATING__COMMENT:
        return getComment();
      case MyDslPackage.RATING__BEWERTET:
        if (resolve) return getBewertet();
        return basicGetBewertet();
      case MyDslPackage.RATING__WRITTEN_BY:
        if (resolve) return getWrittenBy();
        return basicGetWrittenBy();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.RATING__STARS:
        setStars((Integer)newValue);
        return;
      case MyDslPackage.RATING__COMMENT:
        setComment((String)newValue);
        return;
      case MyDslPackage.RATING__BEWERTET:
        setBewertet((Recipe)newValue);
        return;
      case MyDslPackage.RATING__WRITTEN_BY:
        setWrittenBy((Author)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.RATING__STARS:
        setStars(STARS_EDEFAULT);
        return;
      case MyDslPackage.RATING__COMMENT:
        setComment(COMMENT_EDEFAULT);
        return;
      case MyDslPackage.RATING__BEWERTET:
        setBewertet((Recipe)null);
        return;
      case MyDslPackage.RATING__WRITTEN_BY:
        setWrittenBy((Author)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.RATING__STARS:
        return stars != STARS_EDEFAULT;
      case MyDslPackage.RATING__COMMENT:
        return COMMENT_EDEFAULT == null ? comment != null : !COMMENT_EDEFAULT.equals(comment);
      case MyDslPackage.RATING__BEWERTET:
        return bewertet != null;
      case MyDslPackage.RATING__WRITTEN_BY:
        return writtenBy != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (stars: ");
    result.append(stars);
    result.append(", comment: ");
    result.append(comment);
    result.append(')');
    return result.toString();
  }

} //RatingImpl
