/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Author</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Author#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Author#getEmail <em>Email</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Author#getIsOwner <em>Is Owner</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Author#getWrites <em>Writes</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Author#getCalls <em>Calls</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAuthor()
 * @model
 * @generated
 */
public interface Author extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAuthor_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Author#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Email</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Email</em>' attribute.
   * @see #setEmail(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAuthor_Email()
   * @model
   * @generated
   */
  String getEmail();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Author#getEmail <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Email</em>' attribute.
   * @see #getEmail()
   * @generated
   */
  void setEmail(String value);

  /**
   * Returns the value of the '<em><b>Is Owner</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Recipe}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Owner</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Owner</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAuthor_IsOwner()
   * @model
   * @generated
   */
  EList<Recipe> getIsOwner();

  /**
   * Returns the value of the '<em><b>Writes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Rating}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Writes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Writes</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAuthor_Writes()
   * @model containment="true"
   * @generated
   */
  EList<Rating> getWrites();

  /**
   * Returns the value of the '<em><b>Calls</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Recipe}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Calls</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Calls</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAuthor_Calls()
   * @model
   * @generated
   */
  EList<Recipe> getCalls();

} // Author
