/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RecipeManagerImpl <em>Recipe Manager</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RecipeManagerImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRecipeManager()
   * @generated
   */
  int RECIPE_MANAGER = 0;

  /**
   * The feature id for the '<em><b>Authorblock</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE_MANAGER__AUTHORBLOCK = 0;

  /**
   * The feature id for the '<em><b>Recipeblock</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE_MANAGER__RECIPEBLOCK = 1;

  /**
   * The number of structural features of the '<em>Recipe Manager</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE_MANAGER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AuthorblockImpl <em>Authorblock</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AuthorblockImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAuthorblock()
   * @generated
   */
  int AUTHORBLOCK = 1;

  /**
   * The feature id for the '<em><b>Authors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTHORBLOCK__AUTHORS = 0;

  /**
   * The number of structural features of the '<em>Authorblock</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTHORBLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AuthorImpl <em>Author</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AuthorImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAuthor()
   * @generated
   */
  int AUTHOR = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTHOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTHOR__EMAIL = 1;

  /**
   * The feature id for the '<em><b>Is Owner</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTHOR__IS_OWNER = 2;

  /**
   * The feature id for the '<em><b>Writes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTHOR__WRITES = 3;

  /**
   * The feature id for the '<em><b>Calls</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTHOR__CALLS = 4;

  /**
   * The number of structural features of the '<em>Author</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTHOR_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RecipeblockImpl <em>Recipeblock</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RecipeblockImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRecipeblock()
   * @generated
   */
  int RECIPEBLOCK = 3;

  /**
   * The feature id for the '<em><b>Recipes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPEBLOCK__RECIPES = 0;

  /**
   * The number of structural features of the '<em>Recipeblock</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPEBLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RatingImpl <em>Rating</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RatingImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRating()
   * @generated
   */
  int RATING = 4;

  /**
   * The feature id for the '<em><b>Stars</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATING__STARS = 0;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATING__COMMENT = 1;

  /**
   * The feature id for the '<em><b>Bewertet</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATING__BEWERTET = 2;

  /**
   * The feature id for the '<em><b>Written By</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATING__WRITTEN_BY = 3;

  /**
   * The number of structural features of the '<em>Rating</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATING_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RecipeImpl <em>Recipe</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RecipeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRecipe()
   * @generated
   */
  int RECIPE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Author</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__AUTHOR = 1;

  /**
   * The feature id for the '<em><b>Vegan</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__VEGAN = 2;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__DURATION = 3;

  /**
   * The feature id for the '<em><b>Difficulty</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__DIFFICULTY = 4;

  /**
   * The feature id for the '<em><b>Kitchen Utensils</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__KITCHEN_UTENSILS = 5;

  /**
   * The feature id for the '<em><b>Food Category</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__FOOD_CATEGORY = 6;

  /**
   * The feature id for the '<em><b>Ingredients</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__INGREDIENTS = 7;

  /**
   * The number of structural features of the '<em>Recipe</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.KitchenUtensilImpl <em>Kitchen Utensil</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.KitchenUtensilImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getKitchenUtensil()
   * @generated
   */
  int KITCHEN_UTENSIL = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KITCHEN_UTENSIL__NAME = 0;

  /**
   * The number of structural features of the '<em>Kitchen Utensil</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KITCHEN_UTENSIL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FoodCategoryImpl <em>Food Category</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FoodCategoryImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFoodCategory()
   * @generated
   */
  int FOOD_CATEGORY = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOOD_CATEGORY__NAME = 0;

  /**
   * The number of structural features of the '<em>Food Category</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOOD_CATEGORY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.IngridientImpl <em>Ingridient</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.IngridientImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIngridient()
   * @generated
   */
  int INGRIDIENT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGRIDIENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGRIDIENT__AMOUNT = 1;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGRIDIENT__UNIT = 2;

  /**
   * The feature id for the '<em><b>Veganism Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGRIDIENT__VEGANISM_LEVEL = 3;

  /**
   * The feature id for the '<em><b>Recipe</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGRIDIENT__RECIPE = 4;

  /**
   * The number of structural features of the '<em>Ingridient</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGRIDIENT_FEATURE_COUNT = 5;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.RecipeManager <em>Recipe Manager</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recipe Manager</em>'.
   * @see org.xtext.example.mydsl.myDsl.RecipeManager
   * @generated
   */
  EClass getRecipeManager();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.RecipeManager#getAuthorblock <em>Authorblock</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Authorblock</em>'.
   * @see org.xtext.example.mydsl.myDsl.RecipeManager#getAuthorblock()
   * @see #getRecipeManager()
   * @generated
   */
  EReference getRecipeManager_Authorblock();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.RecipeManager#getRecipeblock <em>Recipeblock</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Recipeblock</em>'.
   * @see org.xtext.example.mydsl.myDsl.RecipeManager#getRecipeblock()
   * @see #getRecipeManager()
   * @generated
   */
  EReference getRecipeManager_Recipeblock();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Authorblock <em>Authorblock</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Authorblock</em>'.
   * @see org.xtext.example.mydsl.myDsl.Authorblock
   * @generated
   */
  EClass getAuthorblock();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Authorblock#getAuthors <em>Authors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Authors</em>'.
   * @see org.xtext.example.mydsl.myDsl.Authorblock#getAuthors()
   * @see #getAuthorblock()
   * @generated
   */
  EReference getAuthorblock_Authors();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Author <em>Author</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Author</em>'.
   * @see org.xtext.example.mydsl.myDsl.Author
   * @generated
   */
  EClass getAuthor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Author#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Author#getName()
   * @see #getAuthor()
   * @generated
   */
  EAttribute getAuthor_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Author#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see org.xtext.example.mydsl.myDsl.Author#getEmail()
   * @see #getAuthor()
   * @generated
   */
  EAttribute getAuthor_Email();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Author#getIsOwner <em>Is Owner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Is Owner</em>'.
   * @see org.xtext.example.mydsl.myDsl.Author#getIsOwner()
   * @see #getAuthor()
   * @generated
   */
  EReference getAuthor_IsOwner();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Author#getWrites <em>Writes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Writes</em>'.
   * @see org.xtext.example.mydsl.myDsl.Author#getWrites()
   * @see #getAuthor()
   * @generated
   */
  EReference getAuthor_Writes();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Author#getCalls <em>Calls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Calls</em>'.
   * @see org.xtext.example.mydsl.myDsl.Author#getCalls()
   * @see #getAuthor()
   * @generated
   */
  EReference getAuthor_Calls();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Recipeblock <em>Recipeblock</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recipeblock</em>'.
   * @see org.xtext.example.mydsl.myDsl.Recipeblock
   * @generated
   */
  EClass getRecipeblock();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Recipeblock#getRecipes <em>Recipes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Recipes</em>'.
   * @see org.xtext.example.mydsl.myDsl.Recipeblock#getRecipes()
   * @see #getRecipeblock()
   * @generated
   */
  EReference getRecipeblock_Recipes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Rating <em>Rating</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rating</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rating
   * @generated
   */
  EClass getRating();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Rating#getStars <em>Stars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Stars</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rating#getStars()
   * @see #getRating()
   * @generated
   */
  EAttribute getRating_Stars();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Rating#getComment <em>Comment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comment</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rating#getComment()
   * @see #getRating()
   * @generated
   */
  EAttribute getRating_Comment();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.Rating#getBewertet <em>Bewertet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Bewertet</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rating#getBewertet()
   * @see #getRating()
   * @generated
   */
  EReference getRating_Bewertet();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.Rating#getWrittenBy <em>Written By</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Written By</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rating#getWrittenBy()
   * @see #getRating()
   * @generated
   */
  EReference getRating_WrittenBy();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Recipe <em>Recipe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recipe</em>'.
   * @see org.xtext.example.mydsl.myDsl.Recipe
   * @generated
   */
  EClass getRecipe();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Recipe#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Recipe#getName()
   * @see #getRecipe()
   * @generated
   */
  EAttribute getRecipe_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.Recipe#getAuthor <em>Author</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Author</em>'.
   * @see org.xtext.example.mydsl.myDsl.Recipe#getAuthor()
   * @see #getRecipe()
   * @generated
   */
  EReference getRecipe_Author();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Recipe#getVegan <em>Vegan</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vegan</em>'.
   * @see org.xtext.example.mydsl.myDsl.Recipe#getVegan()
   * @see #getRecipe()
   * @generated
   */
  EAttribute getRecipe_Vegan();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Recipe#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.example.mydsl.myDsl.Recipe#getDuration()
   * @see #getRecipe()
   * @generated
   */
  EAttribute getRecipe_Duration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Recipe#getDifficulty <em>Difficulty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Difficulty</em>'.
   * @see org.xtext.example.mydsl.myDsl.Recipe#getDifficulty()
   * @see #getRecipe()
   * @generated
   */
  EAttribute getRecipe_Difficulty();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Recipe#getKitchenUtensils <em>Kitchen Utensils</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Kitchen Utensils</em>'.
   * @see org.xtext.example.mydsl.myDsl.Recipe#getKitchenUtensils()
   * @see #getRecipe()
   * @generated
   */
  EReference getRecipe_KitchenUtensils();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Recipe#getFoodCategory <em>Food Category</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Food Category</em>'.
   * @see org.xtext.example.mydsl.myDsl.Recipe#getFoodCategory()
   * @see #getRecipe()
   * @generated
   */
  EReference getRecipe_FoodCategory();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Recipe#getIngredients <em>Ingredients</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ingredients</em>'.
   * @see org.xtext.example.mydsl.myDsl.Recipe#getIngredients()
   * @see #getRecipe()
   * @generated
   */
  EReference getRecipe_Ingredients();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.KitchenUtensil <em>Kitchen Utensil</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Kitchen Utensil</em>'.
   * @see org.xtext.example.mydsl.myDsl.KitchenUtensil
   * @generated
   */
  EClass getKitchenUtensil();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.KitchenUtensil#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.KitchenUtensil#getName()
   * @see #getKitchenUtensil()
   * @generated
   */
  EAttribute getKitchenUtensil_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.FoodCategory <em>Food Category</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Food Category</em>'.
   * @see org.xtext.example.mydsl.myDsl.FoodCategory
   * @generated
   */
  EClass getFoodCategory();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.FoodCategory#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.FoodCategory#getName()
   * @see #getFoodCategory()
   * @generated
   */
  EAttribute getFoodCategory_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Ingridient <em>Ingridient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ingridient</em>'.
   * @see org.xtext.example.mydsl.myDsl.Ingridient
   * @generated
   */
  EClass getIngridient();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Ingridient#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Ingridient#getName()
   * @see #getIngridient()
   * @generated
   */
  EAttribute getIngridient_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Ingridient#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see org.xtext.example.mydsl.myDsl.Ingridient#getAmount()
   * @see #getIngridient()
   * @generated
   */
  EAttribute getIngridient_Amount();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Ingridient#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see org.xtext.example.mydsl.myDsl.Ingridient#getUnit()
   * @see #getIngridient()
   * @generated
   */
  EAttribute getIngridient_Unit();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Ingridient#getVeganismLevel <em>Veganism Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Veganism Level</em>'.
   * @see org.xtext.example.mydsl.myDsl.Ingridient#getVeganismLevel()
   * @see #getIngridient()
   * @generated
   */
  EAttribute getIngridient_VeganismLevel();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.Ingridient#getRecipe <em>Recipe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Recipe</em>'.
   * @see org.xtext.example.mydsl.myDsl.Ingridient#getRecipe()
   * @see #getIngridient()
   * @generated
   */
  EReference getIngridient_Recipe();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RecipeManagerImpl <em>Recipe Manager</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RecipeManagerImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRecipeManager()
     * @generated
     */
    EClass RECIPE_MANAGER = eINSTANCE.getRecipeManager();

    /**
     * The meta object literal for the '<em><b>Authorblock</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECIPE_MANAGER__AUTHORBLOCK = eINSTANCE.getRecipeManager_Authorblock();

    /**
     * The meta object literal for the '<em><b>Recipeblock</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECIPE_MANAGER__RECIPEBLOCK = eINSTANCE.getRecipeManager_Recipeblock();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AuthorblockImpl <em>Authorblock</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AuthorblockImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAuthorblock()
     * @generated
     */
    EClass AUTHORBLOCK = eINSTANCE.getAuthorblock();

    /**
     * The meta object literal for the '<em><b>Authors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUTHORBLOCK__AUTHORS = eINSTANCE.getAuthorblock_Authors();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AuthorImpl <em>Author</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AuthorImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAuthor()
     * @generated
     */
    EClass AUTHOR = eINSTANCE.getAuthor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUTHOR__NAME = eINSTANCE.getAuthor_Name();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUTHOR__EMAIL = eINSTANCE.getAuthor_Email();

    /**
     * The meta object literal for the '<em><b>Is Owner</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUTHOR__IS_OWNER = eINSTANCE.getAuthor_IsOwner();

    /**
     * The meta object literal for the '<em><b>Writes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUTHOR__WRITES = eINSTANCE.getAuthor_Writes();

    /**
     * The meta object literal for the '<em><b>Calls</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUTHOR__CALLS = eINSTANCE.getAuthor_Calls();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RecipeblockImpl <em>Recipeblock</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RecipeblockImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRecipeblock()
     * @generated
     */
    EClass RECIPEBLOCK = eINSTANCE.getRecipeblock();

    /**
     * The meta object literal for the '<em><b>Recipes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECIPEBLOCK__RECIPES = eINSTANCE.getRecipeblock_Recipes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RatingImpl <em>Rating</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RatingImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRating()
     * @generated
     */
    EClass RATING = eINSTANCE.getRating();

    /**
     * The meta object literal for the '<em><b>Stars</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RATING__STARS = eINSTANCE.getRating_Stars();

    /**
     * The meta object literal for the '<em><b>Comment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RATING__COMMENT = eINSTANCE.getRating_Comment();

    /**
     * The meta object literal for the '<em><b>Bewertet</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RATING__BEWERTET = eINSTANCE.getRating_Bewertet();

    /**
     * The meta object literal for the '<em><b>Written By</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RATING__WRITTEN_BY = eINSTANCE.getRating_WrittenBy();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RecipeImpl <em>Recipe</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RecipeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRecipe()
     * @generated
     */
    EClass RECIPE = eINSTANCE.getRecipe();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECIPE__NAME = eINSTANCE.getRecipe_Name();

    /**
     * The meta object literal for the '<em><b>Author</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECIPE__AUTHOR = eINSTANCE.getRecipe_Author();

    /**
     * The meta object literal for the '<em><b>Vegan</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECIPE__VEGAN = eINSTANCE.getRecipe_Vegan();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECIPE__DURATION = eINSTANCE.getRecipe_Duration();

    /**
     * The meta object literal for the '<em><b>Difficulty</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECIPE__DIFFICULTY = eINSTANCE.getRecipe_Difficulty();

    /**
     * The meta object literal for the '<em><b>Kitchen Utensils</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECIPE__KITCHEN_UTENSILS = eINSTANCE.getRecipe_KitchenUtensils();

    /**
     * The meta object literal for the '<em><b>Food Category</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECIPE__FOOD_CATEGORY = eINSTANCE.getRecipe_FoodCategory();

    /**
     * The meta object literal for the '<em><b>Ingredients</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECIPE__INGREDIENTS = eINSTANCE.getRecipe_Ingredients();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.KitchenUtensilImpl <em>Kitchen Utensil</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.KitchenUtensilImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getKitchenUtensil()
     * @generated
     */
    EClass KITCHEN_UTENSIL = eINSTANCE.getKitchenUtensil();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute KITCHEN_UTENSIL__NAME = eINSTANCE.getKitchenUtensil_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FoodCategoryImpl <em>Food Category</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FoodCategoryImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFoodCategory()
     * @generated
     */
    EClass FOOD_CATEGORY = eINSTANCE.getFoodCategory();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FOOD_CATEGORY__NAME = eINSTANCE.getFoodCategory_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.IngridientImpl <em>Ingridient</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.IngridientImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIngridient()
     * @generated
     */
    EClass INGRIDIENT = eINSTANCE.getIngridient();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGRIDIENT__NAME = eINSTANCE.getIngridient_Name();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGRIDIENT__AMOUNT = eINSTANCE.getIngridient_Amount();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGRIDIENT__UNIT = eINSTANCE.getIngridient_Unit();

    /**
     * The meta object literal for the '<em><b>Veganism Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGRIDIENT__VEGANISM_LEVEL = eINSTANCE.getIngridient_VeganismLevel();

    /**
     * The meta object literal for the '<em><b>Recipe</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INGRIDIENT__RECIPE = eINSTANCE.getIngridient_Recipe();

  }

} //MyDslPackage
