/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Recipe Manager</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RecipeManager#getAuthorblock <em>Authorblock</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RecipeManager#getRecipeblock <em>Recipeblock</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRecipeManager()
 * @model
 * @generated
 */
public interface RecipeManager extends EObject
{
  /**
   * Returns the value of the '<em><b>Authorblock</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Authorblock</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Authorblock</em>' containment reference.
   * @see #setAuthorblock(Authorblock)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRecipeManager_Authorblock()
   * @model containment="true"
   * @generated
   */
  Authorblock getAuthorblock();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RecipeManager#getAuthorblock <em>Authorblock</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Authorblock</em>' containment reference.
   * @see #getAuthorblock()
   * @generated
   */
  void setAuthorblock(Authorblock value);

  /**
   * Returns the value of the '<em><b>Recipeblock</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Recipeblock</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Recipeblock</em>' containment reference.
   * @see #setRecipeblock(Recipeblock)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRecipeManager_Recipeblock()
   * @model containment="true"
   * @generated
   */
  Recipeblock getRecipeblock();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RecipeManager#getRecipeblock <em>Recipeblock</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Recipeblock</em>' containment reference.
   * @see #getRecipeblock()
   * @generated
   */
  void setRecipeblock(Recipeblock value);

} // RecipeManager
