/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Recipe Manager</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RecipeManager#getAuthors <em>Authors</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RecipeManager#getRecipes <em>Recipes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRecipeManager()
 * @model
 * @generated
 */
public interface RecipeManager extends EObject
{
  /**
   * Returns the value of the '<em><b>Authors</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Author}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Authors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Authors</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRecipeManager_Authors()
   * @model containment="true"
   * @generated
   */
  EList<Author> getAuthors();

  /**
   * Returns the value of the '<em><b>Recipes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Recipe}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Recipes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Recipes</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRecipeManager_Recipes()
   * @model containment="true"
   * @generated
   */
  EList<Recipe> getRecipes();

} // RecipeManager
